version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: encontros_postgres
    restart: always
    environment:
      POSTGRES_USER: encontros
      POSTGRES_PASSWORD: encontros123
      POSTGRES_DB: encontros_db
    ports:
      - "5432:5432"
    volumes:
      - encontros_data:/var/lib/postgresql/data

volumes:
  encontros_data:
